### PR TITLE
Add mask for feature set check.

### PR DESCRIPTION
**Pull request by caternuson**
Potential fix for #19. Adds mask to only check partial feature set value result.

### CODE REVIEW

**Comment by caternuson** [comment]
@ladyada for review. **UNTESTED** (don't have any newer variant boards)

**Comment by Cardenas-Synth** [comment]
thank you for trying to address this. you have the .mpy update for this? i tried using an __init__.py version on my esp32 and i'm getting this error after that line of the feature passes (BTW, thank you for looking into this):

  File "<stdin>", line 1, in <module>
  File "/lib/adafruit_sgp40/__init__.py", line 123, in __init__
  File "/lib/adafruit_sgp40/__init__.py", line 146, in initialize
  File "/lib/adafruit_sgp40/__init__.py", line 293, in _read_word_from_command
OSError: [Errno 116] ETIMEDOUT

**Comment by caternuson** [comment]
Using the .py version is OK. The .mpy is just a "compiled" version that helps for memory constrained boards. If the .py imported without errors, then it's working. You'd want to remove the .mpy version from the CIRCUITPY lib folder though, since .mpy has import precedence over .py. 

The `ETIMEDOUT` issue may be indicating there is more going on. :(

**Comment by Cardenas-Synth** [comment]
Great to know! Thank you for responding so quickly. 

In case this helps, my team has ordered from digikey/adafruit about a couple months back and all spg40s (~10) operated smoothly. We recently ordered from mouser/digikey and all of the boards (16 boards) all failed. Currently, the older ones we still have still work, the newer ones do not. Possibly a bad PCB print? we're returning the ones that didnt work. The position we're at is time sensitive, so we plan on attempting to order some more from a source capable of overnighting to see if we have better luck

Thanks!

Damon

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
@caternuson can merge this to at least resolve the feature change. do you wanna pick up an SGP40 from the shop to try and repro the timeout

**Comment by caternuson** [comment]
@ladyada yep. will do. will wanna check arduino also.

**Comment by Cardenas-Synth** [comment]
I believe i resolved the issue (for at least the code for circuitpython bundle for esp32...maybe similar for RPI)! Please double check, though. I have not verified compatibility with older chipset nor have i fully vetted impact on readings (i assume there will be none, so far it looks good).

With the new chipset, the timeout : self_test = self._read_word_from_command(delay_ms=250)
needed to be extended to 500ms. This was changed with a note in the arduino code (see link below) but not in the circuitpython __init__.py script. I made the update and my code works now!

I changed lines 146 and 207 to the following:
self_test = self._read_word_from_command(delay_ms=500)

I changed this instance in two locations, although i dont know if both are necessary. 

Arduino Change notes
https://github.com/adafruit/Adafruit_SGP40/commit/14449d797463f4e074888bf97a8c9a4345469089

**Comment by ladyada** [comment]
oh yeah that does sound familar! ok new PR made, please take a look!
https://github.com/adafruit/Adafruit_CircuitPython_SGP40/pull/21

**Pull request merged**
